[package]
name = "warp-runner"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]
edition = "2024"

[dependencies]
memmem = "0.1.1"
flate2 = "1.0"
tar = "0.4"
dirs = "6.0.0"
log = "0.4.5"
simple_logger = "5.0.0"
deranged = "=0.4.0"
